### ISSUE TITLE
Välipalautus 2:n vertaisarviointi.

### ISSUE THREAD

**Issue by rigozu9** [RGH84/invoicing-web-application#1]
Moi,
Testasin sovellustasi Fly.iossa ja tässä vähän mietteitä siitä.
Toiminnot joita olit rakentanut toimivat ongelmitta. Sain rekisteröityä uuden käyttäjän, kirjautua sisään, luoda asiakkaan, joka näkyy asiakasrekisterissä, luoda tuotteen joka näkyy tuoterekisterissä ja kirjautua ulos käyttäjältä. Muut toiminnot olivat vielä työn alla. Fly.io käyttö toimii hyvin myös. 

Vaikka toiminnot toiminnot toimivat oikein niin on itse sovelluksen käyttäminen vähän tönkköistä. Suurin ongelma mielestäni oli se että virheen sattuessa käyttäjä heitetään etusivulla takaisin. Olisi sulavempaa näyttää virheilmoitus lomake sivulla jolloin muut tiedot pysyisivät tallessa ja ei tarvitsi uudestaa klikata itseään lomake sivuille. 

Sivustossa ei nyt ole oikein käytetty tyylejäkään, joten se näyttää normaalilta html sivulta. Netistä löytyy hyvää apua css tiedostojen tekemiseen. Esim linkit ovat nyt melkein kiinni toisissaan, joka vaikeuttaa sovelluksen käyttöä. 

Katsoin koodin ja tietokannan myös.
Koodin moduulit toteutettu nätisti pythonin ja sql komentojen avulla. 

Mielestäni error.html käyttöä ei tarvitsisi tässä tehtävässä. Ei ole mukavaa esim kirjoitusvirheen takia mennä uuteen sivuun josta sen jälkeen pitää painaa linkkiä, jotta pääsee etusivulle. routes.py:kin selvenisi selvästi, jos saisit implementoitua jonkin kaltaisen ilmoituksen koodiisi. 

.hmtl tiedostoissa voisi käyttää vähän parempaa koodin muotoilua. Tämä selventäisi paljon koodia, koska nyt monissa tiedostoissa on liikaa rivejä samalla kohdalla koodia. Netistä myös löytyy apua tähän. 

Tietokannan toteutuksesa voisi käyttää vähän enemmän ehtoja. Esim users taulussa voisit laittaa ehdon että salasanan pituus täytyy olla enemmän kuin 4 kirjainta. Tämäkin helpottaisi koodin tekemistä. Nyt routes.py:ssä käytät paljon iffiä, joka vähän sekoittaa koodin lukemista, kun ehtojen laittaminen voisi tehdä muualla. 

Koodi hyvällä mallilla, toiminnot toimivat, mutta käytettävyys ei ole niin mukavaa. Kun lisää vähän tyylejä ja esim sen error notifikaation, niin ohjelma parantuu jo suuresti. Onnea loppu kurssille ja hyvää työtä tähän mennessä!

**Comment by RGH84** [comment]
Kiitoksia hyvästä palautteesta!

**Comment by rigozu9** [comment]
Eipä kestä!
