### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by ellapaella** [RGH84/invoicing-web-application#2]
Pienen testailun jälkeen seuraavia huomiota sovelluksen käyttämisestä:

- Yleisesti jokaisessa kohdassa näytti olevan hyvät tarkistukset lomakkeen täytölle ja tyhjiä tai erikoisia parametreja ei hyväksytty

- Asiakkaan luonti onnistui eikä tullut vastaan virheitä

- Asiakkaan poisto onnistui, eikä jonkun toisen asiakkaan poistaminen onnistunut

- Tuotteen pystyi luomaan miinushinnalla

- Tuotteen luonnin jälkeen sivu siirtyi uuden asiakkaan luonnin lomakkeelle

- Laskun luonnin jälkeen tarkastelusivulla  ei ollut painiketta siirtyä minnekään

- To Do ja viesti kehittäjälle vielä kesken joten ei arvioitu

Koodista ja tietokannasta:

- Koodi näyttää selkeältä ja ymmärrettävältä. Makuasiana ehkä laittaisin useammat if-lauseke tarkistukset, joissa tarkastetaan annettujen tietojen oikeellisuus, erillisiin yksityisiin funktioihin ja kutsuisin sitä sivupyyntö koodin sisällä, mutta tosiaan makuasia

- Tietokanta näytti myös selkeältä ja ei tullut huomattua mitään selkeää omituisuutta mikä pistäisi silmään. Viittaukset ym. näyttivät olevan kohdallaan eikä tiedoissa käytetty rivejä mitkä saisi muista tauluista sql kyselyillä

Onnea loppupalautukseen!

**Comment by RGH84** [comment]
Kiitoksia hyvästä palautteesta!
